version: "3.8"

services:
  web:
    build: .
    image: uj5ghare/django-todo-app:latest
    container_name: django-todo-app-con  
    ports:
      - "8000:8000"
    volumes:
      - ./volume/store_data/db.sqlite3:/data/db.sqlite
    environment:
      - APP_ENV=production
      - LOG_LEVEL=info
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5

