apiVersion: v1
kind: Service
metadata:
  name: todo-svc
  namespace: ns1
  labels:
    app: todo-app
spec:
  selector:
    app: todo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000